// This file is auto-generated by @hey-api/openapi-ts

export type Activity = {
    id?: number;
    title?: string | null;
    dueDate?: string;
    completed?: boolean;
};

export type Author = {
    id?: number;
    idBook?: number;
    firstName?: string | null;
    lastName?: string | null;
};

export type Book = {
    id?: number;
    title?: string | null;
    description?: string | null;
    pageCount?: number;
    excerpt?: string | null;
    publishDate?: string;
};

export type CoverPhoto = {
    id?: number;
    idBook?: number;
    url?: string | null;
};

export type User = {
    id?: number;
    userName?: string | null;
    password?: string | null;
};

export type GetApiV1ActivitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/Activities';
};

export type GetApiV1ActivitiesResponses = {
    /**
     * Success
     */
    200: Array<Activity>;
};

export type GetApiV1ActivitiesResponse = GetApiV1ActivitiesResponses[keyof GetApiV1ActivitiesResponses];

export type PostApiV1ActivitiesData = {
    body?: Activity;
    path?: never;
    query?: never;
    url: '/api/v1/Activities';
};

export type PostApiV1ActivitiesResponses = {
    /**
     * Success
     */
    200: Activity;
};

export type PostApiV1ActivitiesResponse = PostApiV1ActivitiesResponses[keyof PostApiV1ActivitiesResponses];

export type DeleteApiV1ActivitiesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/Activities/{id}';
};

export type DeleteApiV1ActivitiesByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiV1ActivitiesByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/Activities/{id}';
};

export type GetApiV1ActivitiesByIdResponses = {
    /**
     * Success
     */
    200: Activity;
};

export type GetApiV1ActivitiesByIdResponse = GetApiV1ActivitiesByIdResponses[keyof GetApiV1ActivitiesByIdResponses];

export type PutApiV1ActivitiesByIdData = {
    body?: Activity;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/Activities/{id}';
};

export type PutApiV1ActivitiesByIdResponses = {
    /**
     * Success
     */
    200: Activity;
};

export type PutApiV1ActivitiesByIdResponse = PutApiV1ActivitiesByIdResponses[keyof PutApiV1ActivitiesByIdResponses];

export type GetApiV1AuthorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/Authors';
};

export type GetApiV1AuthorsResponses = {
    /**
     * Success
     */
    200: Array<Author>;
};

export type GetApiV1AuthorsResponse = GetApiV1AuthorsResponses[keyof GetApiV1AuthorsResponses];

export type PostApiV1AuthorsData = {
    body?: Author;
    path?: never;
    query?: never;
    url: '/api/v1/Authors';
};

export type PostApiV1AuthorsResponses = {
    /**
     * Success
     */
    200: Author;
};

export type PostApiV1AuthorsResponse = PostApiV1AuthorsResponses[keyof PostApiV1AuthorsResponses];

export type GetApiV1AuthorsAuthorsBooksByIdBookData = {
    body?: never;
    path: {
        idBook: number;
    };
    query?: never;
    url: '/api/v1/Authors/authors/books/{idBook}';
};

export type GetApiV1AuthorsAuthorsBooksByIdBookResponses = {
    /**
     * Success
     */
    200: Array<Author>;
};

export type GetApiV1AuthorsAuthorsBooksByIdBookResponse = GetApiV1AuthorsAuthorsBooksByIdBookResponses[keyof GetApiV1AuthorsAuthorsBooksByIdBookResponses];

export type DeleteApiV1AuthorsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/Authors/{id}';
};

export type DeleteApiV1AuthorsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiV1AuthorsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/Authors/{id}';
};

export type GetApiV1AuthorsByIdResponses = {
    /**
     * Success
     */
    200: Author;
};

export type GetApiV1AuthorsByIdResponse = GetApiV1AuthorsByIdResponses[keyof GetApiV1AuthorsByIdResponses];

export type PutApiV1AuthorsByIdData = {
    body?: Author;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/Authors/{id}';
};

export type PutApiV1AuthorsByIdResponses = {
    /**
     * Success
     */
    200: Author;
};

export type PutApiV1AuthorsByIdResponse = PutApiV1AuthorsByIdResponses[keyof PutApiV1AuthorsByIdResponses];

export type GetApiV1BooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/Books';
};

export type GetApiV1BooksResponses = {
    /**
     * Success
     */
    200: Array<Book>;
};

export type GetApiV1BooksResponse = GetApiV1BooksResponses[keyof GetApiV1BooksResponses];

export type PostApiV1BooksData = {
    body?: Book;
    path?: never;
    query?: never;
    url: '/api/v1/Books';
};

export type PostApiV1BooksResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiV1BooksByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/Books/{id}';
};

export type DeleteApiV1BooksByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiV1BooksByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/Books/{id}';
};

export type GetApiV1BooksByIdResponses = {
    /**
     * Success
     */
    200: Book;
};

export type GetApiV1BooksByIdResponse = GetApiV1BooksByIdResponses[keyof GetApiV1BooksByIdResponses];

export type PutApiV1BooksByIdData = {
    body?: Book;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/Books/{id}';
};

export type PutApiV1BooksByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiV1CoverPhotosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/CoverPhotos';
};

export type GetApiV1CoverPhotosResponses = {
    /**
     * Success
     */
    200: Array<CoverPhoto>;
};

export type GetApiV1CoverPhotosResponse = GetApiV1CoverPhotosResponses[keyof GetApiV1CoverPhotosResponses];

export type PostApiV1CoverPhotosData = {
    body?: CoverPhoto;
    path?: never;
    query?: never;
    url: '/api/v1/CoverPhotos';
};

export type PostApiV1CoverPhotosResponses = {
    /**
     * Success
     */
    200: CoverPhoto;
};

export type PostApiV1CoverPhotosResponse = PostApiV1CoverPhotosResponses[keyof PostApiV1CoverPhotosResponses];

export type GetApiV1CoverPhotosBooksCoversByIdBookData = {
    body?: never;
    path: {
        idBook: number;
    };
    query?: never;
    url: '/api/v1/CoverPhotos/books/covers/{idBook}';
};

export type GetApiV1CoverPhotosBooksCoversByIdBookResponses = {
    /**
     * Success
     */
    200: Array<CoverPhoto>;
};

export type GetApiV1CoverPhotosBooksCoversByIdBookResponse = GetApiV1CoverPhotosBooksCoversByIdBookResponses[keyof GetApiV1CoverPhotosBooksCoversByIdBookResponses];

export type DeleteApiV1CoverPhotosByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/CoverPhotos/{id}';
};

export type DeleteApiV1CoverPhotosByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiV1CoverPhotosByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/CoverPhotos/{id}';
};

export type GetApiV1CoverPhotosByIdResponses = {
    /**
     * Success
     */
    200: CoverPhoto;
};

export type GetApiV1CoverPhotosByIdResponse = GetApiV1CoverPhotosByIdResponses[keyof GetApiV1CoverPhotosByIdResponses];

export type PutApiV1CoverPhotosByIdData = {
    body?: CoverPhoto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/CoverPhotos/{id}';
};

export type PutApiV1CoverPhotosByIdResponses = {
    /**
     * Success
     */
    200: CoverPhoto;
};

export type PutApiV1CoverPhotosByIdResponse = PutApiV1CoverPhotosByIdResponses[keyof PutApiV1CoverPhotosByIdResponses];

export type GetApiV1UsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/Users';
};

export type GetApiV1UsersResponses = {
    /**
     * Success
     */
    200: Array<User>;
};

export type GetApiV1UsersResponse = GetApiV1UsersResponses[keyof GetApiV1UsersResponses];

export type PostApiV1UsersData = {
    body?: User;
    path?: never;
    query?: never;
    url: '/api/v1/Users';
};

export type PostApiV1UsersResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiV1UsersByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/Users/{id}';
};

export type DeleteApiV1UsersByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiV1UsersByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/Users/{id}';
};

export type GetApiV1UsersByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiV1UsersByIdData = {
    body?: User;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/Users/{id}';
};

export type PutApiV1UsersByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'https://fakerestapi.azurewebsites.net' | (string & {});
};